/**
 * ARIA JSON Schema Draft 2020-12 Generator
 * Compiles ARIA AST into a JSON Schema document
 */

import type { AriaModule, TypeDef, WhereClause, RecordField, TypeReference } from "../ast.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generateJsonSchema(module: AriaModule): GeneratedFile {
  const types = module.body.filter((n): n is TypeDef => n.kind === "type");

  const defs: Record<string, unknown> = {};
  for (const t of types) {
    defs[t.name] = buildTypeDef(t, types);
  }

  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `aria://${module.name}`,
    title: module.name,
    description: "Generated by ARIA compiler v0.1.0",
    $defs: defs,
  };

  return {
    path: `${kebabCase(module.name)}.schema.json`,
    content: JSON.stringify(schema, null, 2),
  };
}

// ============================================================================
// SCHEMA BUILDERS
// ============================================================================

function buildTypeDef(t: TypeDef, allTypes: TypeDef[]): Record<string, unknown> {
  switch (t.base) {
    case "Integer":
      return applyWhereClauses({ type: "integer" }, t.whereClauses);
    case "Decimal":
      return applyWhereClauses({ type: "number" }, t.whereClauses);
    case "String":
      return applyWhereClauses({ type: "string" }, t.whereClauses);
    case "Boolean":
      return { type: "boolean" };
    case "DateTime":
      return { type: "string", format: "date-time" };
    case "Record":
      return buildRecord(t, allTypes);
    case "Enum":
      return buildEnum(t);
    case "List":
      return buildList(t);
    default:
      return {};
  }
}

function buildRecord(t: TypeDef, allTypes: TypeDef[]): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const field of t.fields ?? []) {
    properties[field.name] = buildFieldSchema(field, allTypes);
    if (!field.type.isOptional) {
      required.push(field.name);
    }
  }

  const schema: Record<string, unknown> = {
    type: "object",
    properties,
    additionalProperties: false,
  };

  if (required.length > 0) {
    schema.required = required;
  }

  return schema;
}

function buildFieldSchema(field: RecordField, allTypes: TypeDef[]): Record<string, unknown> {
  const ref = field.type;
  const isKnownType = allTypes.some((t) => t.name === ref.name);

  if (isKnownType) {
    return { $ref: `#/$defs/${ref.name}` };
  }

  // Inline primitive for unknown/built-in type references
  return buildInlinePrimitive(ref.name);
}

function buildList(t: TypeDef): Record<string, unknown> {
  if (!t.elementType) {
    return { type: "array" };
  }

  return {
    type: "array",
    items: { $ref: `#/$defs/${t.elementType.name}` },
  };
}

function buildEnum(t: TypeDef): Record<string, unknown> {
  const values = (t.variants ?? []).map((v) => v.name);
  return { enum: values };
}

function buildInlinePrimitive(typeName: string): Record<string, unknown> {
  switch (typeName) {
    case "Integer":
      return { type: "integer" };
    case "Decimal":
      return { type: "number" };
    case "Boolean":
      return { type: "boolean" };
    case "DateTime":
      return { type: "string", format: "date-time" };
    case "String":
    default:
      return { type: "string" };
  }
}

// ============================================================================
// WHERE CLAUSE → JSON SCHEMA KEYWORDS
// ============================================================================

function applyWhereClauses(
  base: Record<string, unknown>,
  whereClauses: WhereClause[]
): Record<string, unknown> {
  const result = { ...base };

  for (const clause of whereClauses) {
    const expr = clause.expression.trim();
    applyClause(result, expr);
  }

  return result;
}

function applyClause(schema: Record<string, unknown>, expr: string): void {
  // length(self) == N  → minLength + maxLength
  let m = expr.match(/^length\(self\)\s*==\s*(\d+)$/);
  if (m) {
    schema.minLength = Number(m[1]);
    schema.maxLength = Number(m[1]);
    return;
  }

  // length(self) >= N  → minLength
  m = expr.match(/^length\(self\)\s*>=\s*(\d+)$/);
  if (m) {
    schema.minLength = Number(m[1]);
    return;
  }

  // length(self) <= N  → maxLength
  m = expr.match(/^length\(self\)\s*<=\s*(\d+)$/);
  if (m) {
    schema.maxLength = Number(m[1]);
    return;
  }

  // self > N  → exclusiveMinimum
  m = expr.match(/^self\s*>\s*(-?\d+(?:\.\d+)?)$/);
  if (m) {
    schema.exclusiveMinimum = Number(m[1]);
    return;
  }

  // self >= N  → minimum
  m = expr.match(/^self\s*>=\s*(-?\d+(?:\.\d+)?)$/);
  if (m) {
    schema.minimum = Number(m[1]);
    return;
  }

  // self < N  → exclusiveMaximum
  m = expr.match(/^self\s*<\s*(-?\d+(?:\.\d+)?)$/);
  if (m) {
    schema.exclusiveMaximum = Number(m[1]);
    return;
  }

  // self <= N  → maximum
  m = expr.match(/^self\s*<=\s*(-?\d+(?:\.\d+)?)$/);
  if (m) {
    schema.maximum = Number(m[1]);
    return;
  }

  // self matches /regex/  → pattern
  m = expr.match(/^self\s+matches\s+\/(.+)\/$/);
  if (m) {
    schema.pattern = m[1];
    return;
  }

  // self starts_with "prefix"  → pattern: ^prefix
  m = expr.match(/^self\s+starts_with\s+"([^"]*)"$/);
  if (m) {
    schema.pattern = `^${escapeRegex(m[1])}`;
    return;
  }
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ============================================================================
// UTILITIES
// ============================================================================

function kebabCase(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}
