/**
 * ARIA Mermaid Diagram Generator
 * Compiles ARIA behavior (state machine) AST nodes into Mermaid stateDiagram-v2
 */

import type { AriaModule, BehaviorDef } from "../ast.js";

export interface MermaidOutput {
  name: string;
  diagram: string;
}

export function generateMermaid(module: AriaModule): MermaidOutput[] {
  const behaviors = module.body.filter(
    (n): n is BehaviorDef => n.kind === "behavior"
  );

  return behaviors.map((b) => ({
    name: b.name,
    diagram: generateStateDiagram(b),
  }));
}

/**
 * Sanitize a string for inclusion in a Mermaid note body.
 * Replaces arrow syntax and characters that confuse the stateDiagram parser.
 */
function sanitizeForNote(s: string): string {
  return s
    .replace(/->/g, "→")        // arrow conflicts with stateDiagram edge syntax
    .replace(/\n/g, " ")        // newlines break note blocks
    .replace(/[{}]/g, "")       // shape syntax characters
    .replace(/\s+/g, " ")       // collapse whitespace
    .trim();
}

function generateStateDiagram(b: BehaviorDef): string {
  const lines: string[] = [];

  lines.push(`stateDiagram-v2`);
  lines.push(``);

  // Initial state
  lines.push(`  [*] --> ${b.initialState}`);
  lines.push(``);

  // Transitions with labels
  for (const t of b.transitions) {
    if (t.when.length > 0) {
      const label = t.when.join(" & ");
      lines.push(`  ${t.from} --> ${t.to}: ${label}`);
    } else {
      lines.push(`  ${t.from} --> ${t.to}`);
    }
  }

  lines.push(``);

  // Terminal states (states with no outgoing transitions)
  const statesWithOutgoing = new Set(b.transitions.map((t) => t.from));
  const terminalStates = b.states.filter(
    (s) => !statesWithOutgoing.has(s.name)
  );
  for (const s of terminalStates) {
    lines.push(`  ${s.name} --> [*]`);
  }

  // Doc comment + invariants merged into a SINGLE note on the initial state
  // (Mermaid stateDiagram-v2 does not support multiple notes on the same side
  // of the same state — must be combined into one block).
  if (b.docComment || b.invariants.length > 0) {
    lines.push(``);
    lines.push(`  note right of ${b.initialState}`);
    if (b.docComment) {
      lines.push(`    ${sanitizeForNote(b.docComment)}`);
    }
    if (b.invariants.length > 0) {
      if (b.docComment) lines.push(`    ---`);
      lines.push(`    Invariants:`);
      for (const inv of b.invariants) {
        lines.push(`    - ${sanitizeForNote(inv.expression)}`);
      }
    }
    lines.push(`  end note`);
  }

  // Forbidden transitions as notes
  if (b.forbidden.length > 0) {
    lines.push(``);
    lines.push(`  note left of ${b.forbidden[0].from}`);
    lines.push(`    Forbidden:`);
    for (const f of b.forbidden) {
      const reason = f.docComment ? ` (${sanitizeForNote(f.docComment)})` : "";
      lines.push(`    ${f.from} → ${f.to}${reason}`);
    }
    lines.push(`  end note`);
  }

  return lines.join("\n");
}

/**
 * Generate a full Markdown document containing all behavior diagrams
 */
export function generateMermaidDoc(module: AriaModule): string {
  const outputs = generateMermaid(module);
  const lines: string[] = [
    `# ${module.name} — State Diagrams`,
    ``,
    `> Generated by ARIA compiler v0.1.0`,
    ``,
  ];

  for (const out of outputs) {
    lines.push(`## ${out.name}`);
    lines.push(``);
    lines.push("```mermaid");
    lines.push(out.diagram);
    lines.push("```");
    lines.push(``);
  }

  return lines.join("\n");
}
