/**
 * ARIA Python + Pydantic v2 Code Generator
 * Compiles ARIA AST into Python 3.11+ types, contracts, and behaviors
 */

import type {
  AriaModule,
  TypeDef,
  ContractDef,
  BehaviorDef,
  WhereClause,
} from "../ast.js";
import { safeName } from "../security.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generatePython(module: AriaModule): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  const types = module.body.filter((n): n is TypeDef => n.kind === "type");
  const contracts = module.body.filter((n): n is ContractDef => n.kind === "contract");
  const behaviors = module.body.filter((n): n is BehaviorDef => n.kind === "behavior");

  files.push({
    path: `${kebab(module.name)}_types.py`,
    content: generateTypesFile(module, types),
  });

  if (contracts.length > 0) {
    files.push({
      path: `${kebab(module.name)}_contracts.py`,
      content: generateContractsFile(module, contracts),
    });
  }

  if (behaviors.length > 0) {
    files.push({
      path: `${kebab(module.name)}_behaviors.py`,
      content: generateBehaviorsFile(module, behaviors),
    });
  }

  return files;
}

// ============================================================================
// IMPORTS HEADER
// ============================================================================

const HEADER = `"""Generated by ARIA compiler v0.1.0"""
from __future__ import annotations
from typing import Annotated, Union, Literal
from enum import Enum
from pydantic import BaseModel, Field, computed_field`;

// ============================================================================
// TYPES FILE
// ============================================================================

function generateTypesFile(module: AriaModule, types: TypeDef[]): string {
  const lines: string[] = [HEADER, ""];

  for (const t of types) {
    if (t.docComment) {
      lines.push(`# ${t.docComment}`);
    }
    lines.push(...generateTypeDef(t));
    lines.push("");
  }

  return lines.join("\n");
}

function generateTypeDef(t: TypeDef): string[] {
  const lines: string[] = [];

  switch (t.base) {
    case "Integer": {
      const fieldArgs = whereClausesToFieldArgs(t.whereClauses);
      if (fieldArgs.length > 0) {
        lines.push(`${t.name} = Annotated[int, Field(${fieldArgs.join(", ")})]`);
      } else {
        lines.push(`${t.name} = int`);
      }
      break;
    }
    case "Decimal": {
      const fieldArgs = whereClausesToFieldArgs(t.whereClauses);
      if (fieldArgs.length > 0) {
        lines.push(`${t.name} = Annotated[float, Field(${fieldArgs.join(", ")})]`);
      } else {
        lines.push(`${t.name} = float`);
      }
      break;
    }
    case "String": {
      const fieldArgs = whereClausesToFieldArgs(t.whereClauses);
      if (fieldArgs.length > 0) {
        lines.push(`${t.name} = Annotated[str, Field(${fieldArgs.join(", ")})]`);
      } else {
        lines.push(`${t.name} = str`);
      }
      break;
    }
    case "Boolean": {
      lines.push(`${t.name} = bool`);
      break;
    }
    case "DateTime": {
      lines.push(`from datetime import datetime`);
      lines.push(`${t.name} = datetime`);
      break;
    }
    case "Record": {
      // Phase 7.2: storage fields go into BaseModel; computed fields become
      // @computed_field @property methods that raise NotImplementedError.
      const storageFields = (t.fields || []).filter((f) => !f.computed);
      const computedFields = (t.fields || []).filter((f) => f.computed);

      lines.push(`class ${t.name}(BaseModel):`);
      if (storageFields.length === 0 && computedFields.length === 0) {
        lines.push(`    pass`);
      } else {
        for (const f of storageFields) {
          const pyType = typeRefToPython(f.type);
          const comment = f.docComment ? `  # ${f.docComment}` : "";
          lines.push(`    ${f.name}: ${pyType}${comment}`);
        }
        for (const f of computedFields) {
          const pyType = typeRefToPython(f.type);
          const sanitized = (f.computed || "").replace(/\n/g, " ").replace(/"""/g, '\\"\\"\\"');
          lines.push(``);
          lines.push(`    @computed_field`);
          lines.push(`    @property`);
          lines.push(`    def ${f.name}(self) -> ${pyType}:`);
          lines.push(`        """@computed ${sanitized}"""`);
          lines.push(`        raise NotImplementedError(`);
          lines.push(`            "Computed field '${f.name}' must be implemented"`);
          lines.push(`        )`);
        }
      }
      break;
    }
    case "Enum": {
      lines.push(`class ${t.name}(str, Enum):`);
      if (t.variants && t.variants.length > 0) {
        for (const v of t.variants) {
          const comment = v.docComment ? `  # ${v.docComment}` : "";
          lines.push(`    ${v.name.toUpperCase()} = "${v.name}"${comment}`);
        }
      } else {
        lines.push(`    pass`);
      }
      break;
    }
    case "List": {
      const elemType = t.elementType ? t.elementType.name : "object";
      lines.push(`${t.name} = list[${elemType}]`);
      break;
    }
  }

  return lines;
}

// ============================================================================
// WHERE CLAUSES → PYDANTIC FIELD ARGS
// ============================================================================

function whereClausesToFieldArgs(whereClauses: WhereClause[]): string[] {
  const args: string[] = [];
  for (const w of whereClauses) {
    args.push(...whereClauseToFieldArgs(w));
  }
  return args;
}

function whereClauseToFieldArgs(w: WhereClause): string[] {
  const expr = w.expression.trim();

  // self > N
  const gtMatch = expr.match(/^self\s*>\s*(\d+)$/);
  if (gtMatch) return [`gt=${gtMatch[1]}`];

  // self >= N
  const gteMatch = expr.match(/^self\s*>=\s*(\d+)$/);
  if (gteMatch) return [`ge=${gteMatch[1]}`];

  // self < N
  const ltMatch = expr.match(/^self\s*<\s*(\d+)$/);
  if (ltMatch) return [`lt=${ltMatch[1]}`];

  // self <= N (supports underscores like 1_000_000)
  const lteMatch = expr.match(/^self\s*<=\s*([\d_]+)$/);
  if (lteMatch) {
    const val = lteMatch[1];
    return [`le=${val.replace(/_/g, "_")}`];
  }

  // length(self) == N
  const lenEqMatch = expr.match(/^length\s*\(\s*self\s*\)\s*==\s*(\d+)$/);
  if (lenEqMatch) return [`min_length=${lenEqMatch[1]}`, `max_length=${lenEqMatch[1]}`];

  // length(self) <= N
  const lenLteMatch = expr.match(/^length\s*\(\s*self\s*\)\s*<=\s*([\d_]+)$/);
  if (lenLteMatch) return [`max_length=${lenLteMatch[1]}`];

  // length(self) >= N
  const lenGteMatch = expr.match(/^length\s*\(\s*self\s*\)\s*>=\s*(\d+)$/);
  if (lenGteMatch) return [`min_length=${lenGteMatch[1]}`];

  // self matches /regex/
  const regexMatch = expr.match(/^self\s+matches\s+\/(.+)\/$/);
  if (regexMatch) {
    const pattern = regexMatch[1].replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return [`pattern=r"${regexMatch[1]}"`];
  }

  return [];
}

// ============================================================================
// CONTRACTS FILE
// ============================================================================

function generateContractsFile(module: AriaModule, contracts: ContractDef[]): string {
  const moduleName = kebab(module.name);
  const lines: string[] = [
    HEADER,
    `from ${moduleName.replace(/-/g, "_")}_types import *`,
    "",
  ];

  for (const c of contracts) {
    lines.push(...generateContract(c));
    lines.push("");
  }

  return lines.join("\n");
}

// Python keywords that need renaming as field names
const PYTHON_KEYWORDS = new Set([
  "from", "import", "class", "def", "return", "if", "else", "elif",
  "for", "while", "in", "is", "not", "and", "or", "pass", "raise",
  "try", "except", "finally", "with", "as", "lambda", "global", "nonlocal",
  "del", "yield", "assert", "break", "continue", "True", "False", "None",
]);

function generateContract(c: ContractDef): string[] {
  const lines: string[] = [];
  const name = c.name;

  // Input model
  lines.push(`class ${name}Input(BaseModel):`);
  if (c.inputs.length > 0) {
    for (const inp of c.inputs) {
      const pyType = typeRefToPython(inp.type);
      if (PYTHON_KEYWORDS.has(inp.name)) {
        lines.push(`    ${inp.name}_: ${pyType} = Field(alias="${inp.name}")`);
      } else {
        lines.push(`    ${inp.name}: ${pyType}`);
      }
    }
  } else {
    lines.push(`    pass`);
  }
  lines.push("");

  // Failure models
  const errorTypes: string[] = [];
  for (const f of c.onFailure) {
    const errName = f.return.type;
    errorTypes.push(errName);
    lines.push(`class ${errName}(BaseModel):`);
    lines.push(`    kind: Literal["${errName}"] = "${errName}"`);
    if (f.return.fields) {
      for (const [key, val] of Object.entries(f.return.fields)) {
        lines.push(`    ${key}: ${inferPyType(val)}`);
      }
    }
    lines.push("");
  }

  // Success model
  lines.push(`class ${name}Success(BaseModel):`);
  lines.push(`    success: Literal[True] = True`);
  lines.push("");

  // Result union
  if (errorTypes.length > 0) {
    const unionParts = [`${name}Success`, ...errorTypes].join(", ");
    lines.push(`${name}Result = Union[${unionParts}]`);
  } else {
    lines.push(`${name}Result = ${name}Success`);
  }
  lines.push("");

  // Precondition guard
  const funcName = snakeCase(name);
  lines.push(`async def ${funcName}(input: ${name}Input) -> ${name}Result:`);
  lines.push(`    # TODO: implement`);
  lines.push(`    raise NotImplementedError()`);
  lines.push("");

  lines.push(`def ${funcName}_requires(input: ${name}Input) -> bool:`);
  if (c.requires.length > 0) {
    for (const r of c.requires) {
      lines.push(`    # ${r.expression}`);
    }
  }
  lines.push(`    return True`);

  return lines;
}

// ============================================================================
// BEHAVIORS FILE
// ============================================================================

function generateBehaviorsFile(module: AriaModule, behaviors: BehaviorDef[]): string {
  const lines: string[] = [HEADER, ""];

  for (const b of behaviors) {
    lines.push(...generateBehavior(b));
    lines.push("");
  }

  return lines.join("\n");
}

function generateBehavior(b: BehaviorDef): string[] {
  const lines: string[] = [];
  const name = b.name;
  const enumName = `${name}State`;
  const constPrefix = snakeCase(name).toUpperCase();

  // State enum
  lines.push(`class ${enumName}(str, Enum):`);
  for (const s of b.states) {
    lines.push(`    ${s.name.toUpperCase()} = "${s.name}"`);
  }
  lines.push("");

  // Initial state constant
  const initialUpper = b.initialState.toUpperCase();
  lines.push(`${constPrefix}_INITIAL = ${enumName}.${initialUpper}`);
  lines.push("");

  // Transitions dict
  lines.push(`${constPrefix}_TRANSITIONS: dict[${enumName}, list[${enumName}]] = {`);
  const transMap: Record<string, string[]> = {};
  for (const s of b.states) {
    transMap[s.name] = [];
  }
  for (const t of b.transitions) {
    if (transMap[t.from] !== undefined) {
      transMap[t.from].push(t.to);
    }
  }
  for (const [state, targets] of Object.entries(transMap)) {
    const stateEnum = `${enumName}.${state.toUpperCase()}`;
    if (targets.length > 0) {
      const targetList = targets.map((t) => `${enumName}.${t.toUpperCase()}`).join(", ");
      lines.push(`    ${stateEnum}: [${targetList}],`);
    } else {
      lines.push(`    ${stateEnum}: [],`);
    }
  }
  lines.push(`}`);
  lines.push("");

  // Transition guard
  const funcName = snakeCase(name);
  lines.push(`def can_${funcName}_transition(from_state: ${enumName}, to_state: ${enumName}) -> bool:`);
  lines.push(`    return to_state in ${constPrefix}_TRANSITIONS.get(from_state, [])`);

  return lines;
}

// ============================================================================
// HELPERS
// ============================================================================

function kebab(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

function snakeCase(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1_$2")
    .replace(/[\s-]+/g, "_")
    .toLowerCase();
}

function typeRefToPython(ref: { name: string; isOptional?: boolean }): string {
  const primitives: Record<string, string> = {
    Integer: "int",
    Decimal: "float",
    String: "str",
    Boolean: "bool",
    DateTime: "datetime",
  };
  const base = primitives[ref.name] ?? ref.name;
  return ref.isOptional ? `${base} | None` : base;
}

function inferPyType(val: string): string {
  if (/\b(balance|amount|total|price|count|quantity)\b/.test(val)) return "float";
  if (/\b(id|email|name|token|address|phone)\b/.test(val)) return "str";
  if (/\b(at|date|time|timestamp)\b/.test(val)) return "datetime";
  if (/\b(is_|has_|can_|active|enabled|verified)\b/.test(val)) return "bool";
  return "object";
}
