/**
 * ARIA Rust Code Generator
 * Compiles ARIA AST into Rust structs, enums, and state machine code
 */

import type {
  AriaModule,
  TypeDef,
  ContractDef,
  BehaviorDef,
  WhereClause,
} from "../ast.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generateRust(module: AriaModule): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  const types = module.body.filter((n): n is TypeDef => n.kind === "type");
  const contracts = module.body.filter((n): n is ContractDef => n.kind === "contract");
  const behaviors = module.body.filter((n): n is BehaviorDef => n.kind === "behavior");

  files.push({
    path: `${kebab(module.name)}-types.rs`,
    content: generateTypesFile(module, types),
  });

  if (contracts.length > 0) {
    files.push({
      path: `${kebab(module.name)}-contracts.rs`,
      content: generateContractsFile(module, contracts),
    });
  }

  if (behaviors.length > 0) {
    files.push({
      path: `${kebab(module.name)}-behaviors.rs`,
      content: generateBehaviorsFile(module, behaviors),
    });
  }

  return files;
}

// ============================================================================
// TYPES FILE
// ============================================================================

function generateTypesFile(module: AriaModule, types: TypeDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Source: ${kebab(module.name)}.aria`,
    `// DO NOT EDIT — regenerate with: aria gen ${kebab(module.name)}.aria`,
    ``,
    `use serde::{Serialize, Deserialize};`,
    ``,
  ];

  for (const t of types) {
    if (t.docComment) {
      lines.push(`/// ${t.docComment}`);
    }
    lines.push(...generateTypeDef(t));
    lines.push(``);
  }

  return lines.join("\n");
}

function generateTypeDef(t: TypeDef): string[] {
  const lines: string[] = [];

  switch (t.base) {
    case "Integer": {
      lines.push(`#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]`);
      lines.push(`pub struct ${t.name}(pub i64);`);
      lines.push(``);
      lines.push(`impl ${t.name} {`);
      lines.push(`    pub fn new(v: i64) -> Result<Self, String> {`);
      for (const w of t.whereClauses) {
        const check = rustValidationCheck(w);
        lines.push(`        if !(${check}) { return Err(${JSON.stringify(w.expression.trim())}.into()); }`);
      }
      lines.push(`        Ok(${t.name}(v))`);
      lines.push(`    }`);
      lines.push(`}`);
      break;
    }
    case "Decimal": {
      lines.push(`#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]`);
      lines.push(`pub struct ${t.name}(pub f64);`);
      lines.push(``);
      lines.push(`impl ${t.name} {`);
      lines.push(`    pub fn new(v: f64) -> Result<Self, String> {`);
      for (const w of t.whereClauses) {
        const check = rustValidationCheck(w);
        lines.push(`        if !(${check}) { return Err(${JSON.stringify(w.expression.trim())}.into()); }`);
      }
      lines.push(`        Ok(${t.name}(v))`);
      lines.push(`    }`);
      lines.push(`}`);
      break;
    }
    case "String": {
      lines.push(`#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]`);
      lines.push(`pub struct ${t.name}(pub String);`);
      lines.push(``);
      lines.push(`impl ${t.name} {`);
      lines.push(`    pub fn new(v: String) -> Result<Self, String> {`);
      for (const w of t.whereClauses) {
        const check = rustStringValidationCheck(w);
        lines.push(`        if !(${check}) { return Err(${JSON.stringify(w.expression.trim())}.into()); }`);
      }
      lines.push(`        Ok(${t.name}(v))`);
      lines.push(`    }`);
      lines.push(`}`);
      break;
    }
    case "Boolean": {
      lines.push(`#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]`);
      lines.push(`pub struct ${t.name}(pub bool);`);
      break;
    }
    case "DateTime": {
      lines.push(`#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]`);
      lines.push(`pub struct ${t.name}(pub String);`);
      break;
    }
    case "Record": {
      // Phase 7.2: storage fields go into the struct; computed fields become
      // impl methods the consumer must fill in.
      const storageFields = (t.fields || []).filter((f) => !f.computed);
      const computedFields = (t.fields || []).filter((f) => f.computed);

      lines.push(`#[derive(Debug, Clone, Serialize, Deserialize)]`);
      lines.push(`pub struct ${t.name} {`);
      for (const f of storageFields) {
        const rustType = typeRefToRust(f.type);
        lines.push(`    pub ${toRustFieldName(f.name)}: ${rustType},`);
      }
      lines.push(`}`);

      if (computedFields.length > 0) {
        lines.push(``);
        lines.push(`impl ${t.name} {`);
        for (const f of computedFields) {
          const rustType = typeRefToRust(f.type);
          const sanitized = (f.computed || "").replace(/\n/g, " ").replace(/`/g, "'");
          lines.push(`    /// Computed: \`${sanitized}\``);
          lines.push(`    pub fn ${toRustFieldName(f.name)}(&self) -> ${rustType} {`);
          lines.push(`        todo!("Computed field '${f.name}': ${sanitized.replace(/"/g, '\\"')}")`);
          lines.push(`    }`);
        }
        lines.push(`}`);
      }
      break;
    }
    case "Enum": {
      lines.push(`#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]`);
      lines.push(`#[serde(rename_all = "snake_case")]`);
      lines.push(`pub enum ${t.name} {`);
      if (t.variants) {
        for (const v of t.variants) {
          lines.push(`    ${toPascalCase(v.name)},`);
        }
      }
      lines.push(`}`);
      break;
    }
    case "List": {
      const elemType = t.elementType ? typeRefToRust(t.elementType) : "serde_json::Value";
      lines.push(`pub type ${t.name} = Vec<${elemType}>;`);
      break;
    }
  }

  return lines;
}

function rustValidationCheck(w: WhereClause): string {
  const expr = w.expression.trim();

  // self > N
  const gtMatch = expr.match(/^self\s*>\s*(\d+)$/);
  if (gtMatch) return `v > ${gtMatch[1]}`;

  // self >= N
  const gteMatch = expr.match(/^self\s*>=\s*(\d+)$/);
  if (gteMatch) return `v >= ${gteMatch[1]}`;

  // self < N
  const ltMatch = expr.match(/^self\s*<\s*(\d+)$/);
  if (ltMatch) return `v < ${ltMatch[1]}`;

  // self <= N (allow underscores in numbers)
  const lteMatch = expr.match(/^self\s*<=\s*([\d_]+)$/);
  if (lteMatch) return `v <= ${lteMatch[1].replace(/_/g, "")}`;

  // self == N
  const eqMatch = expr.match(/^self\s*==\s*(\d+)$/);
  if (eqMatch) return `v == ${eqMatch[1]}`;

  // Fallback: emit TODO comment with safe expression
  const safeExpr = expr.replace(/\*\//g, "* /");
  return `{ /* TODO: ${safeExpr} */ true }`;
}

function rustStringValidationCheck(w: WhereClause): string {
  const expr = w.expression.trim();

  // length(self) <= N
  const lenLteMatch = expr.match(/^length\s*\(\s*self\s*\)\s*<=\s*([\d_]+)$/);
  if (lenLteMatch) return `v.len() <= ${lenLteMatch[1].replace(/_/g, "")}`;

  // length(self) >= N
  const lenGteMatch = expr.match(/^length\s*\(\s*self\s*\)\s*>=\s*(\d+)$/);
  if (lenGteMatch) return `v.len() >= ${lenGteMatch[1]}`;

  // length(self) == N
  const lenEqMatch = expr.match(/^length\s*\(\s*self\s*\)\s*==\s*(\d+)$/);
  if (lenEqMatch) return `v.len() == ${lenEqMatch[1]}`;

  // self matches /regex/
  const regexMatch = expr.match(/^self\s+matches\s+\/(.+)\/$/);
  if (regexMatch) {
    const safeRegex = regexMatch[1].replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    return `regex::Regex::new("${safeRegex}").unwrap().is_match(&v)`;
  }

  // Fallback
  const safeExpr = expr.replace(/\*\//g, "* /");
  return `{ /* TODO: ${safeExpr} */ true }`;
}

function typeRefToRust(ref: { name: string; isOptional?: boolean }): string {
  const primitives: Record<string, string> = {
    Integer: "i64",
    Decimal: "f64",
    String: "String",
    Boolean: "bool",
    DateTime: "String",
  };
  const base = primitives[ref.name] ?? ref.name;
  return ref.isOptional ? `Option<${base}>` : base;
}

// ============================================================================
// CONTRACTS FILE
// ============================================================================

function generateContractsFile(module: AriaModule, contracts: ContractDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Source: ${kebab(module.name)}.aria`,
    `// DO NOT EDIT — regenerate with: aria gen ${kebab(module.name)}.aria`,
    ``,
    `use serde::{Serialize, Deserialize};`,
    `use super::*;`,
    ``,
  ];

  for (const c of contracts) {
    lines.push(...generateContract(c));
    lines.push(``);
  }

  return lines.join("\n");
}

function generateContract(c: ContractDef): string[] {
  const lines: string[] = [];
  const name = c.name;
  const snakeName = toSnakeCase(name);

  // Input struct
  lines.push(`#[derive(Debug, Clone, Serialize, Deserialize)]`);
  lines.push(`pub struct ${name}Input {`);
  for (const inp of c.inputs) {
    lines.push(`    pub ${toRustFieldName(inp.name)}: ${typeRefToRust(inp.type)},`);
  }
  lines.push(`}`);
  lines.push(``);

  // Success struct
  lines.push(`#[derive(Debug, Clone, Serialize, Deserialize)]`);
  lines.push(`pub struct ${name}Success {}`);
  lines.push(``);

  // Error enum
  if (c.onFailure.length > 0) {
    lines.push(`#[derive(Debug, Clone, Serialize, Deserialize)]`);
    lines.push(`pub enum ${name}Error {`);
    for (const f of c.onFailure) {
      lines.push(`    ${f.return.type},`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Async function stub
  const returnOk = `${name}Success`;
  const returnErr = c.onFailure.length > 0 ? `${name}Error` : `String`;
  lines.push(`pub async fn ${snakeName}(input: ${name}Input) -> Result<${returnOk}, ${returnErr}> {`);
  lines.push(`    // TODO: implement`);
  lines.push(`    unimplemented!()`);
  lines.push(`}`);
  lines.push(``);

  // Precondition checker
  lines.push(`pub fn ${snakeName}_requires(input: &${name}Input) -> bool {`);
  for (const r of c.requires) {
    lines.push(`    // ${r.expression}`);
  }
  lines.push(`    true`);
  lines.push(`}`);

  return lines;
}

// ============================================================================
// BEHAVIORS FILE
// ============================================================================

function generateBehaviorsFile(module: AriaModule, behaviors: BehaviorDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Source: ${kebab(module.name)}.aria`,
    `// DO NOT EDIT — regenerate with: aria gen ${kebab(module.name)}.aria`,
    ``,
  ];

  for (const b of behaviors) {
    lines.push(...generateBehavior(b));
    lines.push(``);
  }

  return lines.join("\n");
}

function generateBehavior(b: BehaviorDef): string[] {
  const lines: string[] = [];
  const name = b.name;
  const snakeName = toSnakeCase(name);
  const constName = toSnakeCase(name).toUpperCase();

  // Doc comment + invariants as /// doc comments on the state enum
  // Sanitize newlines (/// comments are line-scoped) and backticks (code fences)
  const sanitizeForRustDoc = (s: string): string =>
    s.replace(/\n/g, " ").replace(/`/g, "'");
  if (b.docComment) {
    lines.push(`/// ${sanitizeForRustDoc(b.docComment)}`);
  }
  if (b.invariants.length > 0) {
    if (b.docComment) lines.push(`///`);
    lines.push(`/// # Invariants`);
    for (const inv of b.invariants) {
      lines.push(`/// - \`${sanitizeForRustDoc(inv.expression)}\``);
    }
  }

  // State enum
  lines.push(`#[derive(Debug, Clone, Copy, PartialEq, Eq)]`);
  lines.push(`pub enum ${name}State {`);
  for (const s of b.states) {
    lines.push(`    ${toPascalCase(s.name)},`);
  }
  lines.push(`}`);
  lines.push(``);

  // Export invariants as a static slice for runtime inspection
  if (b.invariants.length > 0) {
    lines.push(`pub const ${constName}_INVARIANTS: &[&str] = &[`);
    for (const inv of b.invariants) {
      lines.push(`    ${JSON.stringify(inv.expression)},`);
    }
    lines.push(`];`);
    lines.push(``);
  }

  // Initial state constant
  const initialPascal = toPascalCase(b.initialState);
  lines.push(`pub const ${constName}_INITIAL: ${name}State = ${name}State::${initialPascal};`);
  lines.push(``);

  // Transition function
  lines.push(`pub fn can_${snakeName}_transition(from: ${name}State, to: ${name}State) -> bool {`);
  lines.push(`    match (from, to) {`);
  for (const t of b.transitions) {
    const fromPascal = toPascalCase(t.from);
    const toPascal = toPascalCase(t.to);
    lines.push(`        (${name}State::${fromPascal}, ${name}State::${toPascal}) => true,`);
  }
  lines.push(`        _ => false,`);
  lines.push(`    }`);
  lines.push(`}`);

  return lines;
}

// ============================================================================
// HELPERS
// ============================================================================

function toRustFieldName(name: string): string {
  return name;
}

function toPascalCase(s: string): string {
  return s.split(/[_-]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

function toSnakeCase(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();
}

function kebab(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}
