/**
 * ARIA Test Generator
 * Generates Vitest test files from contract examples
 */

import type { AriaModule, ContractDef, BehaviorDef, Example } from "../ast.js";

export function generateTests(module: AriaModule, framework: "vitest" | "jest" = "vitest"): string {
  const contracts = module.body.filter((n): n is ContractDef => n.kind === "contract");
  const behaviors = module.body.filter((n): n is BehaviorDef => n.kind === "behavior");

  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Auto-generated tests from ${kebab(module.name)}.aria examples`,
    `// DO NOT EDIT — regenerate with: aria test ${kebab(module.name)}.aria`,
    ``,
  ];

  if (framework === "vitest") {
    lines.push(`import { describe, it, expect } from "vitest";`);
  }

  lines.push(`import * as contracts from "./${kebab(module.name)}.contracts.js";`);

  if (behaviors.length > 0) {
    lines.push(`import * as behaviors from "./${kebab(module.name)}.behaviors.js";`);
  }

  lines.push(``);

  // Contract tests from examples
  for (const c of contracts) {
    if (c.examples.length === 0 && c.requires.length === 0) continue;

    lines.push(`describe("${c.name}", () => {`);

    // Requires validation tests
    if (c.requires.length > 0) {
      lines.push(`  describe("requires", () => {`);
      for (const r of c.requires) {
        lines.push(`    it("should enforce: ${r.expression}", () => {`);
        lines.push(`      // Precondition: ${r.expression}`);
        lines.push(`      // TODO: provide valid and invalid inputs to test this guard`);
        lines.push(`    });`);
      }
      lines.push(`  });`);
      lines.push(``);
    }

    // Example-based tests
    for (let i = 0; i < c.examples.length; i++) {
      const ex = c.examples[i];
      const label = ex.name || formatExampleLabel(c.name, ex, i);

      lines.push(`  it("${escapeString(label)}", async () => {`);
      lines.push(`    const input = ${formatValue(ex.given, 4)};`);
      lines.push(``);
      lines.push(`    // Verify preconditions`);
      lines.push(`    expect(contracts.${camelCase(c.name)}Requires(input)).toBe(true);`);
      lines.push(``);
      lines.push(`    const result = await contracts.${camelCase(c.name)}(input);`);
      lines.push(``);

      // Generate assertions from then clauses
      for (const a of ex.then) {
        lines.push(`    // assert: ${a.expression}`);
        const assertion = expressionToExpect(a.expression);
        if (assertion) {
          lines.push(`    ${assertion}`);
        }
      }

      lines.push(``);
      lines.push(`    // Verify postconditions`);
      lines.push(`    expect(contracts.${camelCase(c.name)}Ensures(input, result)).toBe(true);`);
      lines.push(`  });`);
      lines.push(``);
    }

    lines.push(`});`);
    lines.push(``);
  }

  // Behavior tests
  for (const b of behaviors) {
    lines.push(`describe("${b.name}", () => {`);

    // Valid transition tests
    lines.push(`  describe("valid transitions", () => {`);
    for (const t of b.transitions) {
      lines.push(`    it("${t.from} -> ${t.to}", () => {`);
      lines.push(`      expect(behaviors.can${b.name}Transition("${t.from}", "${t.to}")).toBe(true);`);
      lines.push(`    });`);
    }
    lines.push(`  });`);
    lines.push(``);

    // Forbidden transition tests
    if (b.forbidden.length > 0) {
      lines.push(`  describe("forbidden transitions", () => {`);
      for (const f of b.forbidden) {
        const label = f.docComment ? `${f.from} -> ${f.to} (${f.docComment})` : `${f.from} -> ${f.to}`;
        lines.push(`    it("should forbid: ${escapeString(label)}", () => {`);
        lines.push(`      expect(behaviors.can${b.name}Transition("${f.from}", "${f.to}")).toBe(false);`);
        lines.push(`    });`);
      }
      lines.push(`  });`);
      lines.push(``);
    }

    // Flow example tests
    for (const flow of b.examples) {
      lines.push(`  it("flow: ${escapeString(flow.name)}", () => {`);
      lines.push(`    const path = ${JSON.stringify(flow.path)};`);
      lines.push(`    for (let i = 0; i < path.length - 1; i++) {`);
      lines.push(`      expect(behaviors.can${b.name}Transition(`);
      lines.push(`        path[i] as behaviors.${b.name}State,`);
      lines.push(`        path[i + 1] as behaviors.${b.name}State`);
      lines.push(`      )).toBe(true);`);
      lines.push(`    }`);
      lines.push(`  });`);
      lines.push(``);
    }

    lines.push(`});`);
    lines.push(``);
  }

  return lines.join("\n");
}

// ============================================================================
// HELPERS
// ============================================================================

function formatExampleLabel(contractName: string, ex: Example, index: number): string {
  const given = Object.entries(ex.given);
  if (given.length <= 2) {
    const params = given.map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(", ");
    return `${contractName}(${params})`;
  }
  return `${contractName} — example ${index + 1}`;
}

function formatValue(val: unknown, indent: number): string {
  return JSON.stringify(val, null, 2).replace(/\n/g, "\n" + " ".repeat(indent));
}

function expressionToExpect(expr: string): string | null {
  // Helper to normalize left-hand side: prefix with result. if not already present
  const normalize = (s: string) => {
    if (s.startsWith("result.")) return s;
    return `result.${s}`;
  };

  // result == ErrorType with field: value  (error type match — check before == catch-all)
  const errorTypeMatch = expr.match(/^result\s*==\s*(\w+)\s+with/);
  if (errorTypeMatch) {
    return `expect(result.kind).toBe("${errorTypeMatch[1]}");`;
  }

  // x != y
  const neqMatch = expr.match(/^([\w.]+)\s*!=\s*(.+)$/);
  if (neqMatch) {
    const left = normalize(neqMatch[1]);
    const right = neqMatch[2].trim();
    return `expect(${left}).not.toBe(${right});`;
  }

  // x >= N
  const gteMatch = expr.match(/^([\w.]+)\s*>=\s*(\d+)$/);
  if (gteMatch) {
    return `expect(${normalize(gteMatch[1])}).toBeGreaterThanOrEqual(${gteMatch[2]});`;
  }

  // x <= N
  const lteMatch = expr.match(/^([\w.]+)\s*<=\s*(\d+)$/);
  if (lteMatch) {
    return `expect(${normalize(lteMatch[1])}).toBeLessThanOrEqual(${lteMatch[2]});`;
  }

  // x > N
  const gtMatch = expr.match(/^([\w.]+)\s*>\s*(\d+)$/);
  if (gtMatch) {
    return `expect(${normalize(gtMatch[1])}).toBeGreaterThan(${gtMatch[2]});`;
  }

  // x < N
  const ltMatch = expr.match(/^([\w.]+)\s*<\s*(\d+)$/);
  if (ltMatch) {
    return `expect(${normalize(ltMatch[1])}).toBeLessThan(${ltMatch[2]});`;
  }

  // not result.success
  const notMatch = expr.match(/^not\s+([\w.]+)$/);
  if (notMatch) {
    return `expect(${normalize(notMatch[1])}).toBeFalsy();`;
  }

  // result.success == true  (equality — catch-all, kept last among comparisons)
  const eqMatch = expr.match(/^([\w.]+)\s*==\s*(.+)$/);
  if (eqMatch) {
    const left = normalize(eqMatch[1]);
    const right = eqMatch[2].trim();
    if (right === "true" || right === "false") {
      return `expect(${left}).toBe(${right});`;
    }
    if (/^\d+$/.test(right)) {
      return `expect(${left}).toBe(${right});`;
    }
    return `expect(${left}).toEqual(${right});`;
  }

  // result.field exists
  const existsMatch = expr.match(/^([\w.]+)\s+exists$/);
  if (existsMatch) {
    return `expect(${normalize(existsMatch[1])}).toBeDefined();`;
  }

  return null;
}

function kebab(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

function camelCase(s: string): string {
  return s[0].toLowerCase() + s.slice(1);
}

function escapeString(s: string): string {
  return s.replace(/"/g, '\\"');
}
