/**
 * ARIA TypeScript + Zod Code Generator
 * Compiles ARIA AST into TypeScript types, Zod schemas, guard functions, and test stubs
 */

import type {
  AriaModule,
  TypeDef,
  ContractDef,
  BehaviorDef,
  RecordField,
  EnumVariant,
  WhereClause,
  Example,
  FailureCase,
  Assertion,
  Step,
} from "../ast.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generateTypeScript(module: AriaModule): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  const types = module.body.filter((n): n is TypeDef => n.kind === "type");
  const contracts = module.body.filter((n): n is ContractDef => n.kind === "contract");
  const behaviors = module.body.filter((n): n is BehaviorDef => n.kind === "behavior");

  // Main types + schemas file
  files.push({
    path: `${kebab(module.name)}.types.ts`,
    content: generateTypesFile(module, types),
  });

  // Contracts file
  if (contracts.length > 0) {
    files.push({
      path: `${kebab(module.name)}.contracts.ts`,
      content: generateContractsFile(module, contracts),
    });
  }

  // Behaviors file
  if (behaviors.length > 0) {
    files.push({
      path: `${kebab(module.name)}.behaviors.ts`,
      content: generateBehaviorsFile(module, behaviors),
    });
  }

  // Test file
  if (contracts.some((c) => c.examples.length > 0)) {
    files.push({
      path: `${kebab(module.name)}.test.ts`,
      content: generateTestFile(module, contracts),
    });
  }

  return files;
}

// ============================================================================
// TYPES FILE
// ============================================================================

function generateTypesFile(module: AriaModule, types: TypeDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Source: ${kebab(module.name)}.aria`,
    `// DO NOT EDIT — regenerate with: aria gen ${kebab(module.name)}.aria`,
    ``,
    `import { z } from "zod";`,
    ``,
  ];

  for (const t of types) {
    if (t.docComment) {
      lines.push(`/** ${t.docComment} */`);
    }
    lines.push(...generateTypeDef(t));
    lines.push(``);
  }

  return lines.join("\n");
}

function generateTypeDef(t: TypeDef): string[] {
  const lines: string[] = [];
  const schemaName = t.name + "Schema";

  // Generic types: emit a plain TypeScript type alias without a Zod schema.
  // Zod does not support generic schemas cleanly — consumers instantiate the
  // generic type with concrete types when using it.
  if (t.typeParams && t.typeParams.length > 0) {
    const params = t.typeParams.join(", ");
    switch (t.base) {
      case "Record": {
        if (t.fields && t.fields.length > 0) {
          lines.push(`export type ${t.name}<${params}> = {`);
          for (const f of t.fields) {
            const fieldType = typeRefToTs(f.type);
            const optional = f.type.isOptional ? "?" : "";
            const comment = f.docComment ? ` // ${f.docComment}` : "";
            lines.push(`  ${f.name}${optional}: ${fieldType};${comment}`);
          }
          lines.push(`};`);
        } else {
          lines.push(`export type ${t.name}<${params}> = Record<string, unknown>;`);
        }
        break;
      }
      case "Enum": {
        if (t.variants && t.variants.length > 0) {
          const variantUnion = t.variants.map((v) => `{ kind: "${v.name}" }`).join(" | ");
          lines.push(`export type ${t.name}<${params}> = ${variantUnion};`);
        } else {
          lines.push(`export type ${t.name}<${params}> = never;`);
        }
        break;
      }
      default: {
        lines.push(`export type ${t.name}<${params}> = unknown;`);
        break;
      }
    }
    return lines;
  }

  switch (t.base) {
    case "Integer": {
      let schema = `z.number().int()`;
      for (const w of t.whereClauses) {
        schema += zodConstraintFromWhere(w, "number");
      }
      lines.push(`export const ${schemaName} = ${schema};`);
      lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
      break;
    }
    case "Decimal": {
      let schema = `z.number()`;
      for (const w of t.whereClauses) {
        schema += zodConstraintFromWhere(w, "number");
      }
      lines.push(`export const ${schemaName} = ${schema};`);
      lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
      break;
    }
    case "String": {
      let schema = `z.string()`;
      for (const w of t.whereClauses) {
        schema += zodConstraintFromWhere(w, "string");
      }
      lines.push(`export const ${schemaName} = ${schema};`);
      lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
      break;
    }
    case "Boolean": {
      lines.push(`export const ${schemaName} = z.boolean();`);
      lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
      break;
    }
    case "DateTime": {
      lines.push(`export const ${schemaName} = z.coerce.date();`);
      lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
      break;
    }
    case "Record": {
      {
        // Phase 7.2: separate storage fields from computed fields.
        // Storage fields go into the Zod schema; computed fields are emitted
        // as an intersection interface populated by the consumer or AI.
        const allFields = t.fields || [];
        const storageFields = allFields.filter((f) => !f.computed);
        const computedFields = allFields.filter((f) => f.computed);

        lines.push(`export const ${schemaName} = z.object({`);
        for (const f of storageFields) {
          const fieldSchema = typeRefToZod(f.type);
          const comment = f.docComment ? ` // ${f.docComment}` : "";
          lines.push(`  ${f.name}: ${fieldSchema},${comment}`);
        }
        lines.push(`});`);

        if (computedFields.length > 0) {
          lines.push(``);
          lines.push(`/**`);
          lines.push(` * Computed fields for ${t.name}.`);
          lines.push(` * Consumers are responsible for populating these derived values.`);
          lines.push(` */`);
          lines.push(`export interface ${t.name}Computed {`);
          for (const f of computedFields) {
            const sanitized = (f.computed || "").replace(/\*\//g, "* /").replace(/\n/g, " ");
            lines.push(`  /** @computed ${sanitized} */`);
            lines.push(`  ${f.name}: ${typeRefToTs(f.type)};`);
          }
          lines.push(`}`);
          lines.push(``);
          lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}> & ${t.name}Computed;`);
        } else {
          lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
        }
      }
      break;
    }
    // end case Record
    case "Enum": {
      if (t.variants && t.variants.length > 0) {
        const values = t.variants.map((v) => `"${v.name}"`).join(", ");
        lines.push(`export const ${schemaName} = z.enum([${values}]);`);
        lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
        // Also export enum-like constants
        lines.push(`export const ${t.name} = {`);
        for (const v of t.variants) {
          const comment = v.docComment ? ` // ${v.docComment}` : "";
          lines.push(`  ${v.name}: "${v.name}" as const,${comment}`);
        }
        lines.push(`} as const;`);
      }
      break;
    }
    case "List": {
      const elemSchema = t.elementType ? `${t.elementType.name}Schema` : "z.unknown()";
      let schema = `z.array(${elemSchema})`;
      for (const w of t.whereClauses) {
        schema += zodConstraintFromWhere(w, "array");
      }
      lines.push(`export const ${schemaName} = ${schema};`);
      lines.push(`export type ${t.name} = z.infer<typeof ${schemaName}>;`);
      break;
    }
  }

  return lines;
}

function zodConstraintFromWhere(w: WhereClause, zodType: string): string {
  // Design decision: Zod constraints are generated from the raw expression string
  // via regex matching. The optional `w.parsedExpression` AST is available but
  // intentionally NOT consumed here — the string approach covers all current
  // patterns (gt, gte, lt, lte, length, regex, starts_with, compound and/or)
  // and is simpler to maintain. Migration to the expression AST is a v0.2 task
  // that would enable arbitrary computed Zod chains but requires a full tree walker.
  const expr = w.expression.trim();

  // Handle compound expressions: "self > 0 and self < 100"
  if (expr.includes(' and ')) {
    const parts = expr.split(' and ').map(p => p.trim());
    return parts.map(part => zodConstraintFromWhere({ kind: 'where', expression: part }, zodType)).join('');
  }
  if (expr.includes(' or ')) {
    // OR constraints can't be simply chained — use refine with actual logic
    const parts = expr.split(' or ').map(p => p.trim());
    const checks = parts.map(p => `/* ${p} */`).join(' || ');
    return `.refine((val) => { ${checks} return true; }, { message: ${JSON.stringify(expr)} })`;
  }

  // self > 0  (special case → .positive() for number, .min(1) for array)
  if (expr.match(/^self\s*>\s*0$/)) {
    if (zodType === "number") return `.positive()`;
    if (zodType === "array") return `.min(1)`;
  }

  // self >= 0  (special case → .nonnegative())
  if (expr.match(/^self\s*>=\s*0$/) && zodType === "number") {
    return `.nonnegative()`;
  }

  // self > N (supports negative numbers)
  const gtMatch = expr.match(/^self\s*>\s*(-?\d+)$/);
  if (gtMatch) {
    const val = parseInt(gtMatch[1]);
    return zodType === "number" ? `.gt(${val})` : "";
  }

  // self >= N (supports negative numbers)
  const gteMatch = expr.match(/^self\s*>=\s*(-?\d+)$/);
  if (gteMatch) {
    const val = parseInt(gteMatch[1]);
    return zodType === "number" ? `.gte(${val})` : "";
  }

  // self < N (supports negative numbers)
  const ltMatch = expr.match(/^self\s*<\s*(-?\d+)$/);
  if (ltMatch) {
    const val = parseInt(ltMatch[1]);
    return zodType === "number" ? `.lt(${val})` : "";
  }

  // self <= N (supports negative numbers and underscores)
  const lteMatch = expr.match(/^self\s*<=\s*(-?[\d_]+)$/);
  if (lteMatch) {
    const val = parseInt(lteMatch[1].replace(/_/g, ""));
    return zodType === "number" ? `.lte(${val})` : "";
  }

  // length(self) == N  (with optional spaces around parens)
  const lenEqMatch = expr.match(/^length\s*\(\s*self\s*\)\s*==\s*(\d+)$/);
  if (lenEqMatch) {
    const val = parseInt(lenEqMatch[1]);
    if (zodType === "string") return `.length(${val})`;
    if (zodType === "array") return `.length(${val})`;
    return "";
  }

  // length(self) <= N  (with optional spaces around parens)
  const lenLteMatch = expr.match(/^length\s*\(\s*self\s*\)\s*<=\s*([\d_]+)$/);
  if (lenLteMatch) {
    const val = parseInt(lenLteMatch[1].replace(/_/g, ""));
    if (zodType === "string") return `.max(${val})`;
    if (zodType === "array") return `.max(${val})`;
    return "";
  }

  // length(self) >= N  (with optional spaces around parens)
  const lenGteMatch = expr.match(/^length\s*\(\s*self\s*\)\s*>=\s*(\d+)$/);
  if (lenGteMatch) {
    const val = parseInt(lenGteMatch[1]);
    if (zodType === "string") return `.min(${val})`;
    if (zodType === "array") return `.min(${val})`;
    return "";
  }

  // self matches /regex/ — sanitize to prevent code injection
  const regexMatch = expr.match(/^self\s+matches\s+\/(.+)\/$/);
  if (regexMatch) {
    const safeRegex = regexMatch[1].replace(/\\/g, "\\\\");
    return zodType === "string" ? `.regex(new RegExp(${JSON.stringify(safeRegex)}))` : "";
  }

  // self starts_with "x" — sanitize to prevent code injection
  const startsMatch = expr.match(/^self\s+starts_with\s+"(.+)"$/);
  if (startsMatch) {
    return zodType === "string" ? `.startsWith(${JSON.stringify(startsMatch[1])})` : "";
  }

  // Unhandled constraint — refine with safe message
  const safeExpr = expr.replace(/\*\//g, "* /");
  return `.refine((val) => { /* TODO: ${safeExpr} */ return true; }, { message: ${JSON.stringify(expr)} })`;
}

function typeRefToTs(ref: { name: string; isOptional?: boolean; typeArgs?: Array<{ name: string }> }): string {
  const primitives: Record<string, string> = {
    Integer: "number",
    Decimal: "number",
    String: "string",
    Boolean: "boolean",
    DateTime: "Date",
  };
  // Handle generic instantiation: Result<Money, Error>
  if (ref.typeArgs && ref.typeArgs.length > 0) {
    const args = ref.typeArgs.map((a) => typeRefToTs({ name: a.name })).join(", ");
    return `${ref.name.split("<")[0]}<${args}>`;
  }
  return primitives[ref.name] ?? ref.name;
}

function typeRefToZod(ref: { name: string; isOptional?: boolean }): string {
  const primitives: Record<string, string> = {
    Integer: "z.number().int()",
    Decimal: "z.number()",
    String: "z.string()",
    Boolean: "z.boolean()",
    DateTime: "z.coerce.date()",
  };
  const base = primitives[ref.name] ?? `${ref.name}Schema`;
  return ref.isOptional ? `${base}.optional()` : base;
}

// ============================================================================
// CONTRACTS FILE
// ============================================================================

function generateContractsFile(module: AriaModule, contracts: ContractDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Source: ${kebab(module.name)}.aria`,
    `// DO NOT EDIT — regenerate with: aria gen ${kebab(module.name)}.aria`,
    ``,
    `import type * as T from "./${kebab(module.name)}.types.js";`,
    ``,
  ];

  for (const c of contracts) {
    lines.push(...generateContract(c));
    lines.push(``);
  }

  return lines.join("\n");
}

function generateContract(c: ContractDef): string[] {
  const lines: string[] = [];
  const name = c.name;
  const camel = camelCase(name);

  // Doc comment
  if (c.docComment || c.deprecated) {
    lines.push(`/**`);
    if (c.docComment) {
      lines.push(` * ${c.docComment}`);
    }
    if (c.deprecated) {
      lines.push(` *`);
      lines.push(` * @deprecated ${c.deprecated}`);
    }
    if (c.requires.length > 0) {
      lines.push(` *`);
      lines.push(` * @requires`);
      for (const r of c.requires) {
        lines.push(` *   - ${r.expression}`);
      }
    }
    if (c.ensures.length > 0) {
      lines.push(` *`);
      lines.push(` * @ensures`);
      for (const e of c.ensures) {
        lines.push(` *   - ${e.expression}`);
      }
    }
    lines.push(` */`);
  }

  // Input interface
  lines.push(`export interface ${name}Input {`);
  for (const inp of c.inputs) {
    lines.push(`  ${inp.name}: T.${inp.type.name};`);
  }
  lines.push(`}`);
  lines.push(``);

  // Error types
  if (c.onFailure.length > 0) {
    for (const f of c.onFailure) {
      lines.push(`export interface ${f.return.type} {`);
      lines.push(`  kind: "${f.return.type}";`);
      if (f.return.fields) {
        for (const [key, val] of Object.entries(f.return.fields)) {
          lines.push(`  ${key}: ${inferTsType(val)};`);
        }
      }
      lines.push(`}`);
      lines.push(``);
    }
  }

  // Result type
  const errorTypes = c.onFailure.map((f) => f.return.type);
  if (errorTypes.length > 0) {
    lines.push(`export type ${name}Result =`);
    lines.push(`  | { success: true; [key: string]: unknown }`);
    for (const errType of errorTypes) {
      lines.push(`  | ${errType}`);
    }
    lines.push(`;`);
  } else {
    lines.push(`export type ${name}Result = { success: true; [key: string]: unknown };`);
  }
  lines.push(``);

  // Precondition guard
  lines.push(`/** Precondition guard — validates requires clauses */`);
  lines.push(`export function ${camel}Requires(input: ${name}Input): boolean {`);
  if (c.requires.length > 0) {
    lines.push(`  // ${c.requires.map((r) => r.expression).join("; ")}`);
  }
  lines.push(`  return true; // TODO: implement requires checks`);
  lines.push(`}`);
  lines.push(``);

  // Postcondition checker
  lines.push(`/** Postcondition checker — validates ensures clauses */`);
  lines.push(`export function ${camel}Ensures(`);
  lines.push(`  input: ${name}Input,`);
  lines.push(`  result: ${name}Result,`);
  lines.push(`): boolean {`);
  if (c.ensures.length > 0) {
    lines.push(`  // ${c.ensures.map((e) => e.expression).join("; ")}`);
  }
  lines.push(`  return true; // TODO: implement ensures checks`);
  lines.push(`}`);
  lines.push(``);

  // Implementation stub (or dispatcher for Phase 7.3 dispatch contracts)
  if (c.dispatch) {
    lines.push(`/**`);
    lines.push(` * Dispatcher — routes to sub-contracts based on \`${c.dispatch.field}\`.`);
    lines.push(` */`);
    lines.push(`export async function ${camel}(`);
    lines.push(`  input: ${name}Input,`);
    lines.push(`): Promise<${name}Result> {`);
    lines.push(`  switch (input.${c.dispatch.field}) {`);
    for (const dc of c.dispatch.cases) {
      const targetCamel = camelCase(dc.contract);
      lines.push(`    case "${dc.value}":`);
      lines.push(`      return ${targetCamel}(input as any);`);
    }
    lines.push(`    default:`);
    lines.push(`      throw new Error(\`Unknown ${c.dispatch.field}: \${input.${c.dispatch.field}}\`);`);
    lines.push(`  }`);
    lines.push(`}`);
  } else {
    lines.push(`/** Implementation — AI generates this from the spec */`);
    lines.push(`export async function ${camel}(`);
    lines.push(`  input: ${name}Input,`);
    lines.push(`): Promise<${name}Result> {`);

    if (c.steps && c.steps.length > 0) {
      lines.push(`  // Orchestration steps:`);
      for (const step of c.steps) {
        lines.push(`  // ${step.number}. ${step.contract}(${Object.values(step.inputs).join(", ")}) -> ${step.resultName}`);
      }
    }

    lines.push(`  throw new Error("Not implemented — generate with: aria implement");`);
    lines.push(`}`);
  }

  return lines;
}

// ============================================================================
// BEHAVIORS FILE
// ============================================================================

function generateBehaviorsFile(module: AriaModule, behaviors: BehaviorDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Source: ${kebab(module.name)}.aria`,
    ``,
  ];

  for (const b of behaviors) {
    lines.push(...generateBehavior(b));
    lines.push(``);
  }

  return lines.join("\n");
}

function generateBehavior(b: BehaviorDef): string[] {
  const lines: string[] = [];
  const name = b.name;

  // Doc comment + invariants as JSDoc on the behavior group
  // Sanitize `*/` to prevent premature comment closure (JSDoc injection)
  const sanitizeForJSDoc = (s: string): string =>
    s.replace(/\*\//g, "* /").replace(/\n/g, " ");
  if (b.docComment || b.invariants.length > 0) {
    lines.push(`/**`);
    if (b.docComment) {
      lines.push(` * ${sanitizeForJSDoc(b.docComment)}`);
    }
    if (b.invariants.length > 0) {
      if (b.docComment) lines.push(` *`);
      for (const inv of b.invariants) {
        lines.push(` * @invariant ${sanitizeForJSDoc(inv.expression)}`);
      }
    }
    lines.push(` */`);
  }

  // State enum
  const stateNames = b.states.map((s) => s.name);
  lines.push(`export const ${name}States = [${stateNames.map((s) => `"${s}"`).join(", ")}] as const;`);
  lines.push(`export type ${name}State = (typeof ${name}States)[number];`);
  lines.push(``);

  // Export invariants as string array for runtime inspection / documentation
  if (b.invariants.length > 0) {
    lines.push(`/** @internal Invariant expressions for documentation/tooling. Format may change. */`);
    lines.push(`export const ${name}Invariants: readonly string[] = [`);
    for (const inv of b.invariants) {
      lines.push(`  ${JSON.stringify(inv.expression)},`);
    }
    lines.push(`] as const;`);
    lines.push(``);
  }

  // Transition map
  lines.push(`export const ${name}Transitions: Record<${name}State, ${name}State[]> = {`);
  const transMap: Record<string, string[]> = {};
  for (const s of stateNames) {
    transMap[s] = [];
  }
  for (const t of b.transitions) {
    if (transMap[t.from]) {
      transMap[t.from].push(t.to);
    }
  }
  for (const [state, targets] of Object.entries(transMap)) {
    lines.push(`  ${state}: [${targets.map((t) => `"${t}"`).join(", ")}],`);
  }
  lines.push(`};`);
  lines.push(``);

  // Forbidden transitions
  if (b.forbidden.length > 0) {
    lines.push(`export const ${name}Forbidden: [${name}State, ${name}State][] = [`);
    for (const f of b.forbidden) {
      const comment = f.docComment ? ` // ${f.docComment}` : "";
      lines.push(`  ["${f.from}", "${f.to}"],${comment}`);
    }
    lines.push(`];`);
    lines.push(``);
  }

  // Transition validator
  lines.push(`export function can${name}Transition(from: ${name}State, to: ${name}State): boolean {`);
  lines.push(`  return ${name}Transitions[from].includes(to);`);
  lines.push(`}`);
  lines.push(``);

  // Initial state
  lines.push(`export const ${name}InitialState: ${name}State = "${b.initialState}";`);

  return lines;
}

// ============================================================================
// TEST FILE
// ============================================================================

function generateTestFile(module: AriaModule, contracts: ContractDef[]): string {
  const lines: string[] = [
    `// Generated by ARIA compiler v0.1.0`,
    `// Auto-generated tests from .aria examples`,
    `// Source: ${kebab(module.name)}.aria`,
    ``,
    `import { describe, it, expect } from "vitest";`,
    `import { ${contracts.map((c) => camelCase(c.name)).join(", ")} } from "./${kebab(module.name)}.contracts.js";`,
    ``,
  ];

  for (const c of contracts) {
    if (c.examples.length === 0) continue;

    lines.push(`describe("${c.name}", () => {`);
    for (let i = 0; i < c.examples.length; i++) {
      const ex = c.examples[i];
      const label = ex.name || `example ${i + 1}`;
      lines.push(`  it("${label}", async () => {`);
      lines.push(`    const input = ${JSON.stringify(ex.given, null, 6).replace(/\n/g, "\n    ")};`);
      lines.push(`    const result = await ${camelCase(c.name)}(input);`);
      for (const a of ex.then) {
        lines.push(`    // assert: ${a.expression}`);
      }
      lines.push(`    expect(result).toBeDefined();`);
      lines.push(`  });`);
      lines.push(``);
    }
    lines.push(`});`);
    lines.push(``);
  }

  return lines.join("\n");
}

// ============================================================================
// HELPERS
// ============================================================================

function kebab(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

function camelCase(s: string): string {
  if (!s) return s;
  const first = s[0].toLowerCase();
  return first + s.slice(1);
}

function inferTsType(val: string): string {
  if (/\b(balance|amount|total|price|count|quantity)\b/.test(val)) return "number";
  if (/\b(id|email|name|token|address|phone)\b/.test(val)) return "string";
  if (/\b(at|date|time|timestamp)\b/.test(val)) return "Date";
  if (/\b(is_|has_|can_|active|enabled|verified)\b/.test(val)) return "boolean";
  return "unknown";
}
