/**
 * ARIA Source Emitter
 * Converts ExtractedSourceFile (from ts-parser) into a .aria source text
 * with skeleton comments where information is missing.
 */

import type {
  ExtractedSourceFile,
  ExtractedType,
  ExtractedFunction,
  ExtractedField,
} from "./ts-parser.js";

export interface EmitOptions {
  moduleName: string;
  target?: string; // typescript by default
  includeJsDoc?: boolean;
}

/**
 * Map a TypeScript type string to an ARIA primitive or composite type.
 * Returns the ARIA type name and a boolean indicating whether it is a primitive.
 */
function tsTypeToAria(tsType: string): string {
  const normalized = tsType.trim();
  // Primitives
  if (/^number$/.test(normalized)) return "Integer"; // best guess (could be Decimal)
  if (/^string$/.test(normalized)) return "String";
  if (/^boolean$/.test(normalized)) return "Boolean";
  if (/^Date$/.test(normalized)) return "DateTime";
  // Arrays: T[] or Array<T>
  const bracketMatch = normalized.match(/^(.+)\[\]$/);
  if (bracketMatch) return `List of ${tsTypeToAria(bracketMatch[1])}`;
  const arrayMatch = normalized.match(/^Array<(.+)>$/);
  if (arrayMatch) return `List of ${tsTypeToAria(arrayMatch[1])}`;
  // Promise<T>
  const promiseMatch = normalized.match(/^Promise<(.+)>$/);
  if (promiseMatch) return tsTypeToAria(promiseMatch[1]);
  // Pass through (custom types like Money, Account)
  return normalized;
}

/**
 * Emit a complete .aria module text from an extracted TypeScript file.
 */
export function emitAria(extracted: ExtractedSourceFile, opts: EmitOptions): string {
  const lines: string[] = [];
  const target = opts.target || "typescript";

  lines.push(`module ${opts.moduleName}`);
  lines.push(`  version "1.0"`);
  lines.push(`  target ${target}`);
  lines.push(``);
  lines.push(`-- Generated by \`aria import\` from ${extracted.filePath}`);
  lines.push(`-- This is a skeleton — refine the requires/ensures/examples manually.`);
  lines.push(``);

  // Types
  if (extracted.types.length > 0) {
    lines.push(`-- ===========================================================`);
    lines.push(`-- TYPES`);
    lines.push(`-- ===========================================================`);
    lines.push(``);
    for (const t of extracted.types) {
      lines.push(...emitType(t, opts));
      lines.push(``);
    }
  }

  // Contracts (from functions)
  if (extracted.functions.length > 0) {
    lines.push(`-- ===========================================================`);
    lines.push(`-- CONTRACTS`);
    lines.push(`-- ===========================================================`);
    lines.push(``);
    for (const fn of extracted.functions) {
      lines.push(...emitContract(fn, opts));
      lines.push(``);
    }
  }

  // Behaviors
  if (extracted.behaviors.length > 0) {
    lines.push(`-- ===========================================================`);
    lines.push(`-- BEHAVIORS`);
    lines.push(`-- ===========================================================`);
    lines.push(``);
    for (const b of extracted.behaviors) {
      lines.push(...emitBehavior(b));
      lines.push(``);
    }
  }

  return lines.join("\n");
}

function emitType(t: ExtractedType, opts: EmitOptions): string[] {
  const lines: string[] = [];
  if (opts.includeJsDoc !== false && t.jsdoc) {
    lines.push(`--- ${sanitizeDocComment(t.jsdoc)}`);
  }

  if (t.kind === "record") {
    lines.push(`type ${t.name} is Record`);
    if (t.fields.length === 0) {
      lines.push(`  -- (no fields)`);
    } else {
      for (const f of t.fields) {
        const ariaType = tsTypeToAria(f.typeName);
        const optional = f.optional ? "?" : "";
        const docInline = f.jsdoc ? `  --- ${sanitizeDocComment(f.jsdoc)}` : "";
        lines.push(`  ${f.name}: ${ariaType}${optional}${docInline}`);
      }
    }
  } else if (t.kind === "enum") {
    lines.push(`type ${t.name} is Enum`);
    if (t.variants.length === 0) {
      lines.push(`  -- (no variants)`);
    } else {
      for (const v of t.variants) {
        lines.push(`  ${v}`);
      }
    }
  } else if (t.kind === "alias") {
    // ARIA does not have type aliases — emit a refined String/Integer with TODO
    const base = tsTypeToAria(t.base);
    lines.push(`type ${t.name} is ${base}`);
    lines.push(`  -- TODO: add where clauses to refine this alias`);
  }

  return lines;
}

function emitContract(fn: ExtractedFunction, opts: EmitOptions): string[] {
  const lines: string[] = [];
  if (opts.includeJsDoc !== false && fn.jsdoc) {
    lines.push(`contract ${capitalize(fn.name)}`);
    lines.push(`  --- ${sanitizeDocComment(fn.jsdoc)}`);
  } else {
    lines.push(`contract ${capitalize(fn.name)}`);
  }

  // Inputs
  if (fn.parameters.length > 0) {
    lines.push(`  inputs`);
    for (const p of fn.parameters) {
      const ariaType = tsTypeToAria(p.typeName);
      const optional = p.optional ? "?" : "";
      lines.push(`    ${p.name}: ${ariaType}${optional}`);
    }
  } else {
    lines.push(`  inputs`);
    lines.push(`    -- (no inputs)`);
  }

  // Requires (TODO — best-effort: empty unless we can deduce from validation calls)
  lines.push(`  requires`);
  lines.push(`    -- TODO: document preconditions (caller obligations)`);

  // Ensures (TODO — best effort: emit return type as a comment)
  lines.push(`  ensures`);
  lines.push(`    -- TODO: document postconditions (function guarantees)`);
  lines.push(`    -- Returns: ${tsTypeToAria(fn.returnType)}`);

  // on_failure (from detected throws)
  if (fn.throws.length > 0) {
    lines.push(`  on_failure`);
    for (const errType of fn.throws) {
      lines.push(`    when -- TODO: document the failure condition`);
      lines.push(`      return ${errType}`);
    }
  }

  // examples (TODO — would need to parse .test.ts files for real examples)
  lines.push(`  examples`);
  lines.push(`    -- TODO: add given/then test cases`);

  return lines;
}

function emitBehavior(b: { name: string; states: string[]; transitions: string[] }): string[] {
  const lines: string[] = [];
  lines.push(`behavior ${b.name}`);
  lines.push(`  --- TODO: detected from enum heuristic — refine manually`);
  lines.push(`  states`);
  for (const s of b.states) {
    lines.push(`    ${s}`);
  }
  lines.push(`  initial ${b.states[0] || "TODO"}`);
  lines.push(`  transitions`);
  if (b.transitions.length === 0) {
    lines.push(`    -- TODO: document state transitions`);
    lines.push(`    -- Example:`);
    if (b.states.length >= 2) {
      lines.push(`    --   ${b.states[0]} -> ${b.states[1]}`);
    }
  } else {
    for (const t of b.transitions) {
      lines.push(`    ${t}`);
    }
  }
  return lines;
}

function capitalize(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}

function sanitizeDocComment(doc: string): string {
  return doc.replace(/\n+/g, " ").replace(/\s+/g, " ").trim();
}
